version: 0.1

phases:
  install:
    commands:
      - echo No commands
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - docker run --rm --name building-the-app -v $(pwd):/usr/src/app -w /usr/src/app node:latest sh deploymentScripts/npmInstallAndBuild.sh
      - mkdir dist -p
      - cp -R style/ dist/
      - cp backgroundImage.jpg bundle.js index.html favicon.ico userDefaultImage.png restaurantDefaultImage.png navigationIcon.svg -t dist/
  build:
    commands:
      - echo Build started on `date`
      - echo serving files to test
      - docker run -v $(pwd)/dist/prod:/usr/share/nginx/html:ro -p 5555:80 -d nginx
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Testing the app
      - echo TODO run app local tests
      - echo TODO add dockerized headless browser to test against
      - echo Uploading to S3
      - printenv > env.txt
      - docker run --env-file ./env.txt --rm --name transferring-files -v $(pwd):/usr/src/app -w /usr/src/app node:latest node deploymentScripts/s3Sync.js